# -*- coding: utf-8 -*-
"""
/***************************************************************************
 KORTxyz
                                 A QGIS plugin
 KORTxyz ProcessingTool 
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2025-10-13
        copyright            : (C) 2025 by Tino Kastbjerg Stigsen
        email                : info@kort.xyz
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""

__author__ = 'Tino Kastbjerg Stigsen'
__date__ = '2025-10-13'
__copyright__ = '(C) 2025 by Tino Kastbjerg Stigsen'


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load KORTxyz class from file KORTxyz.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .kortxyz import KORTxyzPlugin
    return KORTxyzPlugin()
